# Generated by Django 3.2 on 2021-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetable',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
