# Generated by Django 3.2 on 2021-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_requesttable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
