# Generated by Django 3.2 on 2021-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ordertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
