# Generated by Django 3.2 on 2021-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_shoptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='commontable',
            name='pin_code',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
