# Generated by Django 3.2 on 2021-05-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_commontable_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontable',
            name='pin_code',
            field=models.IntegerField(default=0),
        ),
    ]
