# Generated by Django 3.2 on 2021-05-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_alter_commontable_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoptable',
            name='created_on',
        ),
    ]
