# Generated by Django 4.0.4 on 2023-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_remove_shoptable_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptable',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shoptable',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=100, null=True),
        ),
    ]
